#!/bin/bash

echo "simp reporting for duty!"
echo ""
echo "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⣛⡉⠉⢉⠭⠽⠋⠉⠉⠛⠛⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢟⣩⡶⢽⠿⠶⠉⠀⠰⠚⠛⠛⠻⠦⣀⠀⠀⠘⢟⡛⠋⠉⠉⠉⠉⠉⠉⠙⠛⠛⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⣡⠔⠋⠁⡰⠋⠀⠀⠀⠀⠈⠳⡀⠀⠀⠀⠀⣝⠢⠀⠀⠙⢦⡀⠀⠀⠀⠀⠀⠀⢠⡾⠁⣼⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⡿⠁⠴⠃⡀⠀⣰⠁⠀⠀⠀⠀⠀⠀⠀⠹⡄⠀⠀⠀⡈⠳⡄⠀⢀⠀⠙⣄⠀⠀⠀⣠⠴⠃⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⠿⠛⠋⠉⠁⠀⢠⠎⠀⠀⢀⡞⢀⣠⠇⠀⠀⢠⢀⠀⠀⢳⠀⡆⢹⣦⠈⠃⠙⠔⢿⣄⠀⢇⠀⠙⣷⣤⡞⠛⠁⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⡿⢭⡀⠀⠀⠀⠀⠀⢠⠋⠀⠠⢀⠎⢀⡞⢈⠀⡃⠀⠙⠙⠀⠀⠀⡇⠀⠈⡏⢣⡀⠀⣄⠈⢻⡆⠈⢆⠀⠈⢻⠉⠦⣄⡀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣷⡀⠈⠑⠲⣦⣀⣠⠇⠈⠀⠃⡜⠀⡜⠀⣼⠀⡃⠀⠀⠀⠀⠀⠀⢸⡀⠀⢹⠀⢳⣄⠈⢦⠀⣻⡀⠘⠀⠀⠈⢧⠴⠾⢓⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣷⡀⠀⠀⣨⢿⡏⠀⠀⠀⣸⠁⣰⠁⡼⠉⡄⢰⠀⣇⠀⠀⠀⠀⡘⣇⢰⡸⡄⠀⠹⣦⡈⢷⡜⢷⡀⠀⠀⠀⡘⡷⠭⡼⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⣄⠋⠋⡸⠀⠀⠀⢀⡟⠀⡟⣰⡇⠀⣧⢸⡆⠙⡄⠀⠀⢀⡇⢿⣤⣇⡇⠀⠀⢻⣿⣎⠿⣼⣇⠀⠀⠀⢱⢥⣼⣇⢸⣿⣏⣟⣿⣿⣿⣿⣿⣿⣿"
echo "⣿⣿⣿⣿⣿⣿⣿⣷⣠⠃⠀⠀⠀⢸⠃⢸⢃⡟⠀⠀⢸⣇⣿⡀⠸⡄⠐⠊⠀⢸⢱⠀⡇⠉⠉⠙⠛⣟⠳⢽⣿⠀⠀⠀⠀⡞⣿⡞⠀⣿⣷⣾⣿⣿⣟⣿⣿⣿⣿"
echo "⣿⣿⢿⣿⣿⣿⣿⣿⡟⡸⠀⠀⠀⢸⠀⣼⣾⠤⠖⠚⠉⣷⠸⣷⠀⠹⡄⠀⠀⢸⠘⡧⡇⠀⠀⠀⠀⠈⢧⠀⢻⠀⠀⠀⠀⣧⢻⠁⠀⡟⣿⢿⡇⡇⠆⠈⢛⡛⠋"
echo "⢿⣿⣿⣿⢿⣿⣿⣿⢇⡇⠀⡄⠀⢸⡖⠛⡇⠀⠀⠀⠀⠈⢧⢹⣷⡀⠹⡄⠀⢸⡆⢸⡧⠀⠀⠀⠀⠀⠀⢳⣸⡀⠀⢸⠀⢸⡈⣶⣼⡿⢹⠈⠀⠀⠰⠀⡏⠈⠑"
echo "⣿⣿⣿⣟⣯⠉⣽⡿⣸⡇⠀⣷⠀⢸⡇⢰⠁⠀⠀⠀⠐⠒⠺⢧⠹⣷⡦⣙⣆⠈⡇⢤⣶⣾⣿⣿⣿⣿⣷⣦⣽⡇⠀⢸⠀⢸⣧⢹⡿⠁⢸⡄⠀⠀⠀⠀⠀⠀⠀"
echo "⠟⠀⠉⠀⠰⢛⣿⡇⣿⡇⠀⡿⡆⠘⣿⡜⣠⣶⠾⣿⣿⣿⣿⡾⠇⠀⠙⠮⡛⠷⣇⠀⠘⠿⠻⠟⢿⡇⠀⢹⡿⠇⠀⣿⠀⣾⠙⡎⣿⠀⠈⡇⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠰⢄⠀⠉⡇⡏⣷⠀⢣⣧⠀⢹⡿⣿⡇⠀⠻⣏⠿⠿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠶⠶⠾⠀⠀⠛⢹⠀⣼⠇⠀⡿⢡⢇⣿⡄⠀⣇⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⢳⡇⢹⣧⠸⡌⣇⠀⢿⡀⠙⡄⠀⠓⠒⣚⡁⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣏⡼⠋⠀⢀⡷⢃⡾⣿⣄⠀⢸⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⣿⢧⣷⢨⣦⡘⣧⡀⠀⠀⠀⠘⠋⠀⠀⠀⠀⠀⠀⠀⠀⠇⠀⠀⠀⠀⠀⠀⣠⣾⢋⡇⠀⢀⣾⣿⡟⠀⡏⢿⡇⠈⣆⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠘⡆⡇⢸⢻⣀⠙⠿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠊⠉⠁⣼⣠⠖⠉⢸⣿⡇⡆⡇⢸⠙⣆⢹⡄⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣇⢿⢸⡟⣄⠀⠘⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡷⠉⠉⠁⠀⠀⠀⠀⣠⣾⣿⠃⠀⡄⣸⢿⡇⠀⡇⣿⠀⠈⠳⣷⡀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡟⣿⣀⡇⠈⠳⣄⣿⣿⣷⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⡟⠀⣰⢁⣟⢸⡇⢰⡇⠸⡄⠀⠀⠈⠙⠦⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠇⣿⡈⢷⠀⠀⠈⢸⣍⢻⣿⣿⣷⣦⣤⣀⣀⠀⠀⠀⠀⠀⣀⣤⣾⠿⠛⣿⣿⣽⠃⢠⠃⣼⣿⢸⡇⢸⡇⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⢠⣿⡇⢸⣇⠀⢳⡈⣿⣶⡻⣿⣿⣿⣿⣿⡿⢿⣿⣶⣶⣿⡿⠟⠉⠀⢰⣿⣿⡏⢠⠃⣼⣿⣿⣼⠁⢸⠁⠀⢹⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⢸⣿⡇⢸⣿⡄⠀⠳⣿⣿⣿⣾⣿⡿⠛⣩⣇⠀⠙⠻⠟⢉⡀⠀⠀⠀⣸⣿⡿⠀⢁⣾⣿⣿⣿⡇⠀⡾⠀⣿⠘⡆⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⢰⠃⣿⡿⠙⣜⣿⣿⣄⠀⠙⣿⣿⣧⡘⠉⢿⣿⣿⠀⠠⡦⠖⠉⠀⠀⢀⡠⠟⠋⢀⣴⠋⣩⠟⠿⡿⠀⣼⠃⣼⣿⣇⢃⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⡞⢸⡟⡇⠀⡸⢻⣿⣿⣦⣄⠈⢻⣿⠓⠤⠀⠙⠻⢤⣀⠀⢀⣠⠴⠚⢉⣀⡤⣿⠏⢀⡴⠻⣆⣼⣁⣾⡻⣾⣇⢻⢿⣿⡄⠀⠀⠀⠀⠀⠀"
echo ""
echo "======== linux kernel version"
echo ""
uname -a
echo ""
echo "======== linux version"
echo ""
lsb_release -a
echo ""
echo "======== Users with shells"
echo ""
getent passwd | awk -F: 'BEGIN{while(getline s<"/etc/shells") shells[s]=1} ($7 in shells){print $1 ":" $7}'
echo ""
echo "======== list passwd file"
echo ""
cat /etc/passwd
echo ""
echo "======== running processes"
echo ""
ps -ef
echo ""
echo "======== Environment"
echo ""
env
echo ""
echo "======== listening on ports"
echo ""
netstat -na | grep -i listen | grep -v unix
echo ""
echo "======== current user groups"
echo ""
id
echo ""
echo "======== current user sudo privs"
echo ""
sudo -l
echo ""
echo "======== sudo version"
echo "----- check for damn CVEs on chroot to root and others"
echo ""
sudo -V
echo ""
echo "======== check suid, sgid programs and ACLs on files"
echo "----- suid programs"
echo ""
find / -perm /4000 2>/dev/null
echo ""
echo "----- sgid programs"
echo ""
find / -perm /2000 2>/dev/null
echo ""
echo "----- check files with ACLs"
echo ""
getfacl --recursive --skip-base / 2>/dev/null | grep "file:" | cut -d" " -f3 | awk '{print "/"$1}'
echo ""
echo "----- check files or directories readable by the user's group"
echo ""
find / -perm -g=r -not -perm -o=r 2>/dev/null | grep -v /proc | grep -v /sys | grep -v /dev
echo ""
echo "----- check writeable files or directories by the current user"
find / -path /proc -prune -o -type f -perm -o+w 2>/dev/null
echo ""
echo "======== check cronjobs"
echo ""
cat /etc/crontab
